# CI de Nível 03 - Disparo automático em períodos definidos

name: 'Execução Agendada'

# triggers OU gatilhos de execução
# gatilho de exec manual = schedule

on:
  schedule:
    - cron: '27 13 * * *'


jobs:
  # descricao do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo das acoes do job
    steps:

    - uses: actions/checkout@v4

    - name: Instalando Yarn
      run: npm install -g yarn

    - name: Instalando dependências
      run: yarn

    - name: Instalando Playwright
      run: yarn playwright install

    - name: Testes E2E (end-to-end)
      run: yarn run e2e

    # passed, failed, cancelled
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: relatorio-de-testes
        path: ./playwright-report